#!/bin/bash
source global.sh




# Install if not already
if [[ $IP == 127.0.0.1 ]] || [[ ! -f .env ]]; then

	echo "Redirecting to installation..."
	bash install
	exit

fi




# Get data from .env file
source .env




# Builder updates
self_update




# Do the hard pull
sudo bash start --hard