#!/bin/bash
source global.sh


# Do all by default
ACTION=site


# Specific actions
if [[ $1 == git ]] || [[ $1 == server ]] || [[ $1 == permission ]] || [[ $1 == site ]]; then

	ACTION=$1

fi


# Git permissions update
if [[ $ACTION == all ]] || [[ $ACTION == git ]]; then

	git_permission_update site/.git

fi


# Server permission update
if [[ $ACTION == all ]] || [[ $ACTION == server ]]; then

	server_permission_update /var/www/html/

fi


# Local file permission update
if [[ $ACTION == all ]] || [[ $ACTION == permission ]]; then

	permission_update site/

fi


# Local file permission update
if [[ $ACTION == site ]]; then

	git_permission_update site/.git
	permission_update site/

fi