#!/bin/bash
source global.sh




# Install if not already
if [[ $IP == 127.0.0.1 ]] || [[ ! -f .env ]]; then

	echo "Redirecting to installation..."
	bash install
	exit

fi




# Get data from .env file
source .env




# Builder updates
self_update




# Open that IP slot
ifconfig lo0 alias $IP up
echo -e "'${IP}' is now available ... ${GREEN}done${RESET}"




# DETECT DB CHANGES
DB_FILE=site/database/dump/wordpress_data.sql
DB_SUM1=$(md5 -r $DB_FILE)


# Pulling latest changes from git
(
	cd site/
	echo "Checking the latest remote changes..."
	git pull
	echo -e "Git pull complete ... ${GREEN}done${RESET}"
)


# DETECT DB CHANGES
DB_SUM2=$(md5 -r $DB_FILE)
if [[ $DB_SUM1 != $DB_SUM2 ]]; then


	echo "DB changed."


	echo "Closing server..."
	docker-compose down
	echo -e "Server is down ... ${GREEN}done${RESET}"


	echo "Old data removing..."
	rm -rf site/database/mysql/
	echo -e "Remove old data ... ${GREEN}done${RESET}"


	echo "Site is building again..."
	docker-compose up -d
	echo -e "Build server again ... ${GREEN}done${RESET}"


	# Check MySQL to be ready
	while ! docker-compose exec db mysqladmin --user=root --password=password --host "${IP}" ping --silent &> /dev/null ; do
		echo "Waiting for database connection..."
		sleep 3
	done
	echo -e "MySQL is ready! ... ${GREEN}done${RESET}"


	# Do the URL replacements if needed
	if [[ $DOMAIN != $OLD_DOMAIN ]]; then


		echo -e "DB replacements starting ($OLD_DOMAIN -> $DOMAIN)..."
		wp search-replace "${OLD_DOMAIN}" "${DOMAIN}" --recurse-objects --report-changed-only --skip-columns=guid --skip-tables=wp_users
		echo -e "DB replacements from '$OLD_DOMAIN' to '$DOMAIN' ... ${GREEN}done${RESET}"


	fi


else


	echo "DB is identical."


	# Start the docker containers
	echo "Starting the server..."
	docker-compose up -d
	echo -e "Server is ${GREEN}up${RESET}"


fi




# Server permission update
# bash permission-fix




# PRINT THE SITE INFO
echo ""
echo ""
echo "== Site Info ===================="
echo ""
echo "Admin Page: http://${DOMAIN}"
echo "IP: ${IP}"
echo ""
echo "================================="
echo ""
echo ""














# If package.json exist in theme folder
if [[ -f site/wp/wp-content/themes/${SLUG}/package.json ]]; then



	# If Gulp not installed, build the gulp
	if [[ ! -d site/wp/wp-content/themes/${SLUG}/node_modules ]] || [[ ! -d site/wp/wp-content/themes/${SLUG}/node_modules/gulp ]]; then


		# RUN THE GULP
		echo "GULP is installing..."
		docker-compose run --no-deps --rm gulp npm run build
		echo -e "GULP installed ... ${GREEN}done${RESET}"


	fi



	# If Gulp file exist in theme folder
	if [[ -f site/wp/wp-content/themes/${SLUG}/gulpfile.js ]]; then


		# RUN THE GULP
		echo "GULP is running..."
		docker-compose run --no-deps --rm gulp npm start


	fi



fi