#!/bin/bash
source global.sh




# Install if not already
if [[ $IP == 127.0.0.1 ]] || [[ ! -f .env ]]; then

	echo "Redirecting to installation..."
	bash install
	exit

fi




# Get data from .env file
source .env




# Builder updates
self_update




# Open that IP slot
ifconfig lo0 alias $IP up
echo -e "'${IP}' is now available ... ${GREEN}done${RESET}"




# Pull the changes
if [[ $1 == --hard ]]; then

	sudo bash pull

else

	sudo bash pull --hard

fi




# Server permission update
# bash permission-fix




# PRINT THE SITE INFO
echo -e "${GREEN}Site is up!${RESET}"
echo ""
echo ""
echo "== Site Info ===================="
echo ""
echo "Admin Page: http://${DOMAIN}"
echo "IP: ${IP}"
echo ""
echo "================================="
echo ""
echo ""




# Install NPM for Gulp
install_npm