#!/bin/bash
source global.sh




# Builder updates
self_update




# Install if not already
if [[ ! -f .env ]]; then

	echo "This project not installed yet."
	exit

fi


# Get data from .env file
source .env




# Delete the server
echo "Server is closing..."
docker-compose down




# Remove the host to the list
sudo bash config/etc-hosts.sh -remove $DOMAIN
killall -HUP mDNSResponder
echo -e "'$DOMAIN - $IP' Removed from the etc/hosts file ... ${GREEN}done${RESET}"




# Delete the .env file
rm .env
echo -e ".env file removed from the builder ... ${GREEN}done${RESET}"




echo -e "${GREEN}Project Uninstalled${RESET}"