#!/bin/bash
source global.sh



# Builder updates
self_update



# Install if not already
if [[ ! -f .env ]]; then

	echo "This project not installed yet."
	exit

fi



# Get data from .env file
source .env



# Delete the server
echo "Server is closing..."
docker-compose down



# Remove the host to the list
sudo bash config/etc-hosts.sh -remove $DOMAIN
killall -HUP mDNSResponder



# Delete the DB files
rm -rf site/database/mysql/
echo -e "MySQL files removed ... ${GREEN}done${RESET}"


(
	cd site/wp/
	find . -mindepth 1 -maxdepth 1 ! -name 'wp-content' -exec rm -rf '{}' \;
)
echo -e "WP core files removed ... ${GREEN}done${RESET}"


# Delete the .env file
rm .env
echo -e ".env file removed from the builder ... ${GREEN}done${RESET}"



echo -e "${GREEN}Project Uninstalled${RESET}"